"""empty message

Revision ID: 947fe934d32f
Revises: c01a254aa2ff
Create Date: 2021-08-05 14:30:06.831932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '947fe934d32f'
down_revision = 'c01a254aa2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assetname', sa.String(length=64), nullable=True),
    sa.Column('registertime', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_assetname'), 'asset', ['assetname'], unique=False)
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assetid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('applytime', sa.DateTime(), nullable=True),
    sa.Column('expecttime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['assetid'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_assetid'), 'application', ['assetid'], unique=False)
    op.create_index(op.f('ix_application_id'), 'application', ['id'], unique=False)
    op.create_index(op.f('ix_application_userid'), 'application', ['userid'], unique=False)
    op.add_column('user', sa.Column('role', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('department', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(collation='utf8_bin', length=120), nullable=True))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'department')
    op.drop_column('user', 'role')
    op.drop_index(op.f('ix_application_userid'), table_name='application')
    op.drop_index(op.f('ix_application_id'), table_name='application')
    op.drop_index(op.f('ix_application_assetid'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_assetname'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
