"""users jwt

Revision ID: b70965f8d14d
Revises: 947fe934d32f
Create Date: 2021-08-16 09:18:21.848160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b70965f8d14d'
down_revision = '947fe934d32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    # ### end Alembic commands ###
